# Generated by Django 4.2.1 on 2023-11-11 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("singers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("image", models.ImageField(blank=True, null=True, upload_to="songs")),
                ("genre", models.CharField(max_length=120)),
                (
                    "singer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="singers.singer",
                    ),
                ),
            ],
            options={
                "unique_together": {("singer", "title")},
            },
        ),
    ]
